import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  mainSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // '.' means the current docs folder
    },
    // Additional items can be added here
    // {
    //   type: 'category',
    //   label: 'Guides',
    //   items: ['guides/getting-started'],
    // },
  ],
};

export default sidebars;
